### ISSUE TITLE
Proposal: automatic projection from declared fields

### ISSUE THREAD

**Issue by bohoffi** [afollestad/inquiry#1]
I'm currently playing with your library and ran into an issue when working with a content provider which is not explained in the readme:

I have the following model class
```java
public class ExternalImage extends GalleryItem {

    @Column
    public int _id;
    @Column
    public String _data;
    @Column
    public int _size;
    @Column
    public String mime_type;
    @Column
    public String title;
}
```

When using Inquiry with the following statement
```java
Uri imagesUri = Uri.parse("content://media/external/images/media");
return Inquiry.get()
    .selectFrom(imagesUri, ExternalImage.class)
    .all();
```

I get the following error
> java.lang.IllegalStateException: No field found in de.bohoffi.simplegallery.data.models.ExternalImage for column _display_name (of type REAL)
>     at com.afollestad.inquiry.ClassRowConverter.cursorToCls(ClassRowConverter.java:191)

when running through the line
`Field e = cls.getDeclaredField(columnName);`

It seems to me that the `ClassRowConverter` wants to map every column to the row object if there is no projection handed to Inquiry because if I call the above statement with a projection `.projection("_id", "_data", "_size", "mime_type", "title")` which contains at least one but not more than the declared fields of the mapped class it runs fine and returns the expected result.

### Here is the proposal
If it's possible it would be great to generate a default projection from the mapped class and use it in the ClassRowConverter. If a user provides a custom projection the default one would be replaced.

This would save a lot of biolerplate code when working with system content providers because a user does not have to map every single column or provide a deault projection by himself which has to be maintained every time the user adds/removes a mapped field.

**Comment by afollestad** [comment]
That's a good idea, I'll have that in the next update

**Comment by afollestad** [comment]
It's available now in release 1.2.0.

**Comment by bohoffi** [comment]
You're the best :D

Your efforts to deliver the best experience for developers using your apps are amazing!

**Comment by afollestad** [comment]
Thank you 😀
