### ISSUE TITLE
Ability to delete row at position

### ISSUE THREAD

**Issue by chilldelta** [afollestad/inquiry#11]
Reading the delete rows code syntax, your library is taking in the **database table name** and the **pojo class** but the setup seems to be saying something different. Maybe an update to the setup might be in order to ensure people that wish to use the library in the near feature don't get confused.

Also is it possible to add removing the rows according to the position or can the library already do this? I achieved this with the default database by doing

```java
Cursor cursor = sqliteDatabase.query(DraftContract.DraftEntry.TABLE_NAME,
    null, null, null, null, null, null);
cursor.moveToPosition(position);
int id = cursor.getInt(cursor.getColumnIndex("_id"));
String[] whereClauseArgument = new String[1];
whereClauseArgument[0] = Integer.toString(id);

sqliteDatabase.delete(DraftContract.DraftEntry.TABLE_NAME, "_id=?", whereClauseArgument); 
```

with this library and trying something like this which throws errors

```java
Inquiry.get()
    .deleteFrom(Draft_DB, GateHelper.class)
    .where("_id = ?", position)
    .run();
```

**Comment by afollestad** [comment]
Updated your description with syntax highlighting.

So basically, you want to be able to delete rows at a specific position? The problem with this is that not every table has an `_id` row, so it would only work for some people.

**Comment by chilldelta** [comment]
Am aware. Thanks for considering it as an enhancement to this library.

**Comment by chilldelta** [comment]
Thanks for considering this as an enhancement to the library.

**Comment by afollestad** [comment]
https://github.com/afollestad/inquiry/releases/tag/2.0.1
