### ISSUE TITLE
IndexOutOfBoundsException error using atPosition() 

### ISSUE THREAD

**Issue by chilldelta** [afollestad/inquiry#12]
Am trying to use the newly added atPosition(int position) to perform a specific operation (delete) both from my selected item in a recyclerviewer and the database but am getting IndexOutOfBoundsException. Have looked through my code to check for issues but it seems am not correctly guided on how this method works. Maybe a sample or a snippet might suffice. In anycase, this his how am trying to delete a row.

                List<Integer> selectedItemPositions = adapter.getSelectedItems();
                int currentPosition;
                for (int i = selectedItemPositions.size() - 1; i >= 0; i--) {
                    currentPosition = selectedItemPositions.get(i);
                    deleteDraftDetails(currentPosition);
                    adapter.removeData(currentPosition);
                }

The delete row method for database

       private void deleteDraftDetails(int position) {
        Inquiry.get()
                .deleteFrom(Draft_DB, GateHelper.class)
                .atPosition(position)
                .run();
         }

**Comment by afollestad** [comment]
That's not a secure way to delete items. 

As items are removed, the count is changed so positions are no longer valid.

**Comment by afollestad** [comment]
E.g.:

1 2 3 4 5

Delete position 2

1 2 4 5

Delete position 2

1 2 5

Delete position 2

1 2

Delete position 2

Out of bounds
