### ISSUE TITLE
Question: Does inquiry work for nested classes?

### ISSUE THREAD

**Issue by HeinrichReimer** [afollestad/inquiry#13]
Does inquiry work for nested classes?
I have the following classes:

**Subject.java**

````java
public class Subject {
    @Column(name = "_id", primaryKey = true, notNull = true, autoIncrement = true)
    protected long id;
    @Column(name = "shorthand")
    protected String shorthand;
    @Column(name = "full_name")
    protected String fullName;
    @Column(name = "color")
    protected int color;
    ...
}
````

**TeacherSubject.java**`

````java
public class TeacherSubject extends Subject {
    @Column(name = "teacher")
    protected String teacher;
    @Column(name = "room")
    protected String room;
    ...
}
````

Would an insertion of `TeacherSubject`s also insert the `shorthand`,`fullName` and `color` into the same table?

**Expected table structure**

|_id|shorthand|full_name|color|teacher|room|
|---|---|---|---|---|---|
|1|En|Englisch|0xffcc0000|Do|B-123|
|2|Ph|Physik|0xffff8acd|Sm|A204|

**Comment by afollestad** [comment]
Yes, it should in theory work since Inquiry retrieves parent class fields. I haven't verified that though.

**Comment by afollestad** [comment]
Actually I know it works, since I believe that's used in Impression

**Comment by HeinrichReimer** [comment]
Thank you and keep up your great work!

**Comment by afollestad** [comment]
https://github.com/afollestad/inquiry/releases/tag/3.0.0
