### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by HeinrichReimer** [afollestad/inquiry#15]
Is there a way to have multiple instances of `Inquiry` running at a time?
**Example:**
I have a `Service` that is running in background and sometimes needs to write to a database. An `Activity` is reading from the database every time it is opened or a refresh is triggered. The problem here is that I can't use `Inquiry.init()` and `Inquiry.deinit()` in my `Activity`'s/`Service`'s lifecycle methods as the activity may still be running when the service has finished its work. It shouldn't be any problem if I had one `Inquiry` instance for the service and one for the activity

**Comment by HeinrichReimer** [comment]
This has been fixed in my fork: https://github.com/HeinrichReimer/inquiry/issues/2

**Comment by afollestad** [comment]
Done

**Comment by afollestad** [comment]
https://github.com/afollestad/inquiry/releases/tag/3.0.0
