### ISSUE TITLE
Add support for WHERE IN clause

### ISSUE THREAD

**Issue by ritdaw** [afollestad/inquiry#16]
Would be super useful to have, however I gather the rawQuery method has to be used.
i.e. delete where id in(1,2,3,4)

```java
int[ ] deleteIds = { 3,4,5 };
Integer deletedCount = Inquiry.get()
		.deleteFrom("people", Person.class)
		.where("_id in(?)", deleteIds)
		.run();
```

**Comment by afollestad** [comment]
Added in the latest release, see the tutorial on the front page for details. A lot has changed in version 3.0.1 and 3.1.0.

**Comment by ritdaw** [comment]
Awesome thanks!
