### ISSUE TITLE
onUpgrade functionality ?

### ISSUE THREAD

**Issue by aitorvs** [afollestad/inquiry#2]
Hi there,

first, thanks for the library. I really like it.

I was wondering whether you plan to add onUpgrade functionality to handle database upgrades. I've been using your library and is something I found missing for my usage. 

I wouldn't mind opening a PR myself when I have a little time to implement it, in case is something you wanna add and don't have in the pipeline just yet.

**Comment by afollestad** [comment]
This is now available in version 1.3.0, the third parameter in `init(Context, String, int)` is the database version.

**Comment by aitorvs** [comment]
Thanks! Will have a look at it.

**Comment by ericwjr** [comment]
This feature could use a couple lines in Readme.  If one adds columns in the class without updating DB version, what happens?  Would that trigger an onupgrade?  I wouldn't be mad if it automatically added the column with empty data for all existing rows... I've seen that done in Nosql dbs and I like it.
