### ISSUE TITLE
Foreign DB not dropped when Parent DB is dropped

### ISSUE THREAD

**Issue by ToysoftInc** [afollestad/inquiry#25]
I'm using the latest library and running into a problem where if the Parent table is dropped the foreign table is not dropped. (appears!)

I ran the sample app which comes with the library and running into the same problem.

Here is what I did.

1. Run the sample app and make sure it is working.  The logcat should output

"MainActivity", "Parent 1 has 5 children."

2. Modify the app and in the create() add this

        Inquiry.get(MainActivity.this).dropTable(Parent.class);

3. Run the app again and now the logcat shows Parent 1 has 10 children.

"MainActivity", "Parent 1 has 10 children."

Anyone know what is going on?

**Comment by afollestad** [comment]
You'll need to manually drop all related tables.
