### ISSUE TITLE
Updating already inserted entities with a where statement

### ISSUE THREAD

**Issue by ToysoftInc** [afollestad/inquiry#26]
I'm using the latest library and can't figure out why getting this error message.

@Table
public class ContactDBRecord {

    public ContactDBRecord() { }

    public ContactDBRecord(String name) {
        this.mName = name;
    }

    @Column(name = "_id", primaryKey = true, notNull = true, autoIncrement = true)
    public long id;

    @Column public String mName;
}

Statement: 

// contact  is ContactDBRecord  and has valid data

            Integer updatedCount = Inquiry.get(context)
                    .update(ContactDBRecord.class)
                    .values(new ContactDBRecord[] { contact })
                    .where("mName = ?", "Bart")
                    .run();

Error: 

java.lang.IllegalStateException: You want to update rows which have IDs, but specified a where statement.

**Comment by afollestad** [comment]
This is currently intended behavior.

When you update objects that exist in the database already (objects that were just inserted or queried), Inquiry updates each of these rows by their IDs directly, allowing you to do updates without specifying a where statement at all.
