### ISSUE TITLE
Request: Sample app

### ISSUE THREAD

**Issue by msegmx** [afollestad/inquiry#29]
Thanks for this great library.

A few things are still unclear, e.g. how to create database, what if Inquiry.get(..) is called twice, how to drop database, etc.

Is it possible to get a sample app  with basic and advanced features implemented ?

**Comment by afollestad** [comment]
I don't think a sample is completely necessary for a library like this.

The questions above should all be answered by the tutorial. 
* Databases are created automatically when you build an Inquiry instance, if the database doesn't already exist. (https://github.com/afollestad/inquiry#quick-setup)
* Repeated calls to `.get()` returns the same instance which is created when you build an instance.

**Comment by afollestad** [comment]
There are a lot of examples in both the tutorial and all of the unit/Android tests which are in the code.

**Comment by msegmx** [comment]
Thanks for the quick answer.
I'm already studying the code further, but a few more question :

I need the access the db in onCreate.
- Should I call newInstance in onCreate and onResume ?

- Normally I would create the Db in Application.onCreate. Would you recommend it or is it not necessary anymore ?

- I don't understand the call to Inquiry.destroy(this) in onPause (within an if (isFinishing()) statement), wouldn't if enough to call Inquiry.destroy(this) in onDestroy of an Activity ?

**Comment by afollestad** [comment]
* You should only call newInstance() once for a single database, you can use `get()` to retrieve that instance from anywhere else.
* That would work, you could then use `get()` from anywhere in your app.
* It depends on where you create the instance. If you create an instance from `onCreate()` of an `Activity`, you'd want to call `destroy(this)` from `onDestroy()` of the same `Activity`.

**Comment by msegmx** [comment]
I have one last question :
you said in the tutorial :

> It's very important that you destroy() instances when you are done with them. This closes the database lock and makes sure any memory references are cleaned up.

If I call destroy(), the next time I need an instance, should I call newInstance or simply get() ?

Really last question; what about transactions : I need to insert rows into multiple table inside a transaction, are transactions supported at this time ?

**Comment by afollestad** [comment]
`destroy()` will completely remove the instance reference so `get()` would return null.

Transactions aren't supported _yet_.
