### ISSUE TITLE
Feature request: dynamic/calculated column

### ISSUE THREAD

**Issue by bohoffi** [afollestad/inquiry#3]
Hi @afollestad,

I would like to propose a new feature: dynamic/calculated column.
It would work like the `@DynamicColumn` feature from sprinkles.

*You can see how to use it:*

**Declaration (link: Sprinkles sample)**
https://github.com/emilsjolander/sprinkles/blob/master/sample/src/se/emilsjolander/sprinkles/sample/models/Note.java

**Declaration (my code)**
```java
@Table("Shelves")
public class Shelf extends Model {

    public static final String PROPERTY_KEY_BOOK_COUNT = "book_count";
    ...
    @DynamicColumn(PROPERTY_KEY_BOOK_COUNT)
    private int bookCount;
    ...
}
```

**Usage (link: Sprinkles sample)**
https://github.com/emilsjolander/sprinkles/blob/master/sample/src/se/emilsjolander/sprinkles/sample/NotesActivity.java

**Usage (my code)**
```java
Query.many(Shelf.class, "select Shelves.*," + 
    " (select count(*) from Books where Books.shelf_id = Shelves.id) as book_count from Shelves where book_count > 0")
    .get();
```

I really would like to migrate to Inquiry but my app is currently working with such a dynamic column as you can see above.

If you won't add such a feature it will be ok but I would have to do many manual updates on the according objects.

**Comment by afollestad** [comment]
This would be a bit difficult since Inquiry doesn't have the user pass in SQL statements.

**Comment by bohoffi** [comment]
Yes, I know but maybe you could build a new method 'withSubselect' or something like that?
The difficult part may be that a subselect could query a different entity than the original query so that the class and the table name of every additional entity must be provided.
