### ISSUE TITLE
Know when inserting in finished

### ISSUE THREAD

**Issue by MuhamedFathy** [afollestad/inquiry#36]
I have a large amount of items more than 5000, The insertion takes a lot of time to finish, Is there any way to know if the items finished inserting or not?

**Comment by afollestad** [comment]
Well, `run()` is a syncronous method so when it exits it's done.

**Comment by afollestad** [comment]
The async version has a callback also.

**Comment by MuhamedFathy** [comment]
I tried `run()` but when I exit the app or minimize it then get to on resume again I got this exception

    FATAL EXCEPTION: Thread-15
            Process: com.afaqy.afaqynet, PID: 22655
            java.lang.IllegalStateException: You must initialize your Inquiry instance with a non-null database name.
            at com.afollestad.inquiry.Inquiry._getDatabase(Inquiry.java:50)
            at com.afollestad.inquiry.Query.run(Query.java:468)
            at com.afollestad.inquiry.Query$2.run(Query.java:607)
            at java.lang.Thread.run(Thread.java:761)
