### ISSUE TITLE
Specify column name

### ISSUE THREAD

**Issue by plusCubed** [afollestad/inquiry#5]
i.e. `@Column(MediaStore.Images.Media.DATA)`

Haven't done much annotation processing before, but I feel queasy just using the field name for  content providers when there are defined constants.

**Comment by afollestad** [comment]
I've been meaning to do this but hadn't gotten around to it.

Implementing it now

**Comment by afollestad** [comment]
@plusCubed release 1.4.0 includes this feature, `@Column(name = MediaStore.Images.Media.DATA)`
